#pragma once

#define BAGL_FONT_ID_MASK                   0x0FFF
#define BAGL_FONT_ALIGNMENT_HORIZONTAL_MASK 0xC000
#define BAGL_FONT_ALIGNMENT_LEFT            0x0000
#define BAGL_FONT_ALIGNMENT_RIGHT           0x4000
#define BAGL_FONT_ALIGNMENT_CENTER          0x8000
#define BAGL_FONT_ALIGNMENT_VERTICAL_MASK   0x3000
#define BAGL_FONT_ALIGNMENT_TOP             0x0000
#define BAGL_FONT_ALIGNMENT_BOTTOM          0x1000
#define BAGL_FONT_ALIGNMENT_MIDDLE          0x2000

#define BAGL_ENCODING_LATIN1 0

#define BAGL_FONT_OPEN_SANS_LIGHT_14px BAGL_FONT_OPEN_SANS_REGULAR_11_14PX

typedef enum {
    BAGL_FONT_LUCIDA_CONSOLE_8PX,
    BAGL_FONT_OPEN_SANS_LIGHT_16_22PX,
    BAGL_FONT_OPEN_SANS_REGULAR_8_11PX,
    BAGL_FONT_OPEN_SANS_REGULAR_10_13PX,
    BAGL_FONT_OPEN_SANS_REGULAR_11_14PX,
    BAGL_FONT_OPEN_SANS_REGULAR_13_18PX,
    BAGL_FONT_OPEN_SANS_REGULAR_22_30PX,
    BAGL_FONT_OPEN_SANS_SEMIBOLD_8_11PX,
    BAGL_FONT_OPEN_SANS_EXTRABOLD_11px = 8u, // validated on nano s
    BAGL_FONT_OPEN_SANS_LIGHT_16px = 9u,     // validated on nano s
    BAGL_FONT_OPEN_SANS_REGULAR_11px = 10u,  // validated on nano s
    BAGL_FONT_OPEN_SANS_SEMIBOLD_10_13PX,
    BAGL_FONT_OPEN_SANS_SEMIBOLD_11_16PX,
    BAGL_FONT_OPEN_SANS_SEMIBOLD_13_18PX,
    BAGL_FONT_SYMBOLS_0,
    BAGL_FONT_SYMBOLS_1,
    BAGL_FONT_LAST // MUST ALWAYS BE THE LAST, FOR AUTOMATED INVALID VALUE CHECKS
} bagl_font_id_e;
