# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='message.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rmessage.proto\"\x13\n\x11MessageGetVersion\"%\n\x12ResponseGetVersion\x12\x0f\n\x07version\x18\x01 \x01(\t\"\x12\n\x10MessageGetPubKey\"#\n\x11ResponseGetPubKey\x12\x0e\n\x06pubkey\x18\x01 \x01(\x0c\"\x1b\n\rMessageSignTx\x12\n\n\x02tx\x18\x01 \x01(\x0c\"5\n\x0eResponseSignTx\x12\x10\n\x08\x61pproved\x18\x01 \x01(\x08\x12\x11\n\tsignature\x18\x02 \x01(\x0c\"\"\n\rResponseError\x12\x11\n\terror_msg\x18\x01 \x01(\t\"\x91\x01\n\x07Message\x12)\n\x0bget_version\x18\x01 \x01(\x0b\x32\x12.MessageGetVersionH\x00\x12\'\n\nget_pubkey\x18\x02 \x01(\x0b\x32\x11.MessageGetPubKeyH\x00\x12!\n\x07sign_tx\x18\x03 \x01(\x0b\x32\x0e.MessageSignTxH\x00\x42\x0f\n\rmessage_oneof\"\xb6\x01\n\x08Response\x12*\n\x0bget_version\x18\x01 \x01(\x0b\x32\x13.ResponseGetVersionH\x00\x12(\n\nget_pubkey\x18\x02 \x01(\x0b\x32\x12.ResponseGetPubKeyH\x00\x12\"\n\x07sign_tx\x18\x03 \x01(\x0b\x32\x0f.ResponseSignTxH\x00\x12\x1f\n\x05\x65rror\x18\x04 \x01(\x0b\x32\x0e.ResponseErrorH\x00\x42\x0f\n\rmessage_oneofb\x06proto3'
)




_MESSAGEGETVERSION = _descriptor.Descriptor(
  name='MessageGetVersion',
  full_name='MessageGetVersion',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=36,
)


_RESPONSEGETVERSION = _descriptor.Descriptor(
  name='ResponseGetVersion',
  full_name='ResponseGetVersion',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='ResponseGetVersion.version', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=75,
)


_MESSAGEGETPUBKEY = _descriptor.Descriptor(
  name='MessageGetPubKey',
  full_name='MessageGetPubKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=95,
)


_RESPONSEGETPUBKEY = _descriptor.Descriptor(
  name='ResponseGetPubKey',
  full_name='ResponseGetPubKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='pubkey', full_name='ResponseGetPubKey.pubkey', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=97,
  serialized_end=132,
)


_MESSAGESIGNTX = _descriptor.Descriptor(
  name='MessageSignTx',
  full_name='MessageSignTx',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='tx', full_name='MessageSignTx.tx', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=134,
  serialized_end=161,
)


_RESPONSESIGNTX = _descriptor.Descriptor(
  name='ResponseSignTx',
  full_name='ResponseSignTx',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='approved', full_name='ResponseSignTx.approved', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='signature', full_name='ResponseSignTx.signature', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=163,
  serialized_end=216,
)


_RESPONSEERROR = _descriptor.Descriptor(
  name='ResponseError',
  full_name='ResponseError',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='error_msg', full_name='ResponseError.error_msg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=218,
  serialized_end=252,
)


_MESSAGE = _descriptor.Descriptor(
  name='Message',
  full_name='Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='get_version', full_name='Message.get_version', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='get_pubkey', full_name='Message.get_pubkey', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sign_tx', full_name='Message.sign_tx', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='message_oneof', full_name='Message.message_oneof',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=255,
  serialized_end=400,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='get_version', full_name='Response.get_version', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='get_pubkey', full_name='Response.get_pubkey', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sign_tx', full_name='Response.sign_tx', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='error', full_name='Response.error', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='message_oneof', full_name='Response.message_oneof',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=403,
  serialized_end=585,
)

_MESSAGE.fields_by_name['get_version'].message_type = _MESSAGEGETVERSION
_MESSAGE.fields_by_name['get_pubkey'].message_type = _MESSAGEGETPUBKEY
_MESSAGE.fields_by_name['sign_tx'].message_type = _MESSAGESIGNTX
_MESSAGE.oneofs_by_name['message_oneof'].fields.append(
  _MESSAGE.fields_by_name['get_version'])
_MESSAGE.fields_by_name['get_version'].containing_oneof = _MESSAGE.oneofs_by_name['message_oneof']
_MESSAGE.oneofs_by_name['message_oneof'].fields.append(
  _MESSAGE.fields_by_name['get_pubkey'])
_MESSAGE.fields_by_name['get_pubkey'].containing_oneof = _MESSAGE.oneofs_by_name['message_oneof']
_MESSAGE.oneofs_by_name['message_oneof'].fields.append(
  _MESSAGE.fields_by_name['sign_tx'])
_MESSAGE.fields_by_name['sign_tx'].containing_oneof = _MESSAGE.oneofs_by_name['message_oneof']
_RESPONSE.fields_by_name['get_version'].message_type = _RESPONSEGETVERSION
_RESPONSE.fields_by_name['get_pubkey'].message_type = _RESPONSEGETPUBKEY
_RESPONSE.fields_by_name['sign_tx'].message_type = _RESPONSESIGNTX
_RESPONSE.fields_by_name['error'].message_type = _RESPONSEERROR
_RESPONSE.oneofs_by_name['message_oneof'].fields.append(
  _RESPONSE.fields_by_name['get_version'])
_RESPONSE.fields_by_name['get_version'].containing_oneof = _RESPONSE.oneofs_by_name['message_oneof']
_RESPONSE.oneofs_by_name['message_oneof'].fields.append(
  _RESPONSE.fields_by_name['get_pubkey'])
_RESPONSE.fields_by_name['get_pubkey'].containing_oneof = _RESPONSE.oneofs_by_name['message_oneof']
_RESPONSE.oneofs_by_name['message_oneof'].fields.append(
  _RESPONSE.fields_by_name['sign_tx'])
_RESPONSE.fields_by_name['sign_tx'].containing_oneof = _RESPONSE.oneofs_by_name['message_oneof']
_RESPONSE.oneofs_by_name['message_oneof'].fields.append(
  _RESPONSE.fields_by_name['error'])
_RESPONSE.fields_by_name['error'].containing_oneof = _RESPONSE.oneofs_by_name['message_oneof']
DESCRIPTOR.message_types_by_name['MessageGetVersion'] = _MESSAGEGETVERSION
DESCRIPTOR.message_types_by_name['ResponseGetVersion'] = _RESPONSEGETVERSION
DESCRIPTOR.message_types_by_name['MessageGetPubKey'] = _MESSAGEGETPUBKEY
DESCRIPTOR.message_types_by_name['ResponseGetPubKey'] = _RESPONSEGETPUBKEY
DESCRIPTOR.message_types_by_name['MessageSignTx'] = _MESSAGESIGNTX
DESCRIPTOR.message_types_by_name['ResponseSignTx'] = _RESPONSESIGNTX
DESCRIPTOR.message_types_by_name['ResponseError'] = _RESPONSEERROR
DESCRIPTOR.message_types_by_name['Message'] = _MESSAGE
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MessageGetVersion = _reflection.GeneratedProtocolMessageType('MessageGetVersion', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGEGETVERSION,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:MessageGetVersion)
  })
_sym_db.RegisterMessage(MessageGetVersion)

ResponseGetVersion = _reflection.GeneratedProtocolMessageType('ResponseGetVersion', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSEGETVERSION,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:ResponseGetVersion)
  })
_sym_db.RegisterMessage(ResponseGetVersion)

MessageGetPubKey = _reflection.GeneratedProtocolMessageType('MessageGetPubKey', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGEGETPUBKEY,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:MessageGetPubKey)
  })
_sym_db.RegisterMessage(MessageGetPubKey)

ResponseGetPubKey = _reflection.GeneratedProtocolMessageType('ResponseGetPubKey', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSEGETPUBKEY,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:ResponseGetPubKey)
  })
_sym_db.RegisterMessage(ResponseGetPubKey)

MessageSignTx = _reflection.GeneratedProtocolMessageType('MessageSignTx', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGESIGNTX,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:MessageSignTx)
  })
_sym_db.RegisterMessage(MessageSignTx)

ResponseSignTx = _reflection.GeneratedProtocolMessageType('ResponseSignTx', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSESIGNTX,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:ResponseSignTx)
  })
_sym_db.RegisterMessage(ResponseSignTx)

ResponseError = _reflection.GeneratedProtocolMessageType('ResponseError', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSEERROR,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:ResponseError)
  })
_sym_db.RegisterMessage(ResponseError)

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:Message)
  })
_sym_db.RegisterMessage(Message)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:Response)
  })
_sym_db.RegisterMessage(Response)


# @@protoc_insertion_point(module_scope)
