/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: message.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "message.pb-c.h"
void   message_get_version__init
                     (MessageGetVersion         *message)
{
  static const MessageGetVersion init_value = MESSAGE_GET_VERSION__INIT;
  *message = init_value;
}
size_t message_get_version__get_packed_size
                     (const MessageGetVersion *message)
{
  assert(message->base.descriptor == &message_get_version__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t message_get_version__pack
                     (const MessageGetVersion *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &message_get_version__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t message_get_version__pack_to_buffer
                     (const MessageGetVersion *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &message_get_version__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MessageGetVersion *
       message_get_version__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MessageGetVersion *)
     protobuf_c_message_unpack (&message_get_version__descriptor,
                                allocator, len, data);
}
void   message_get_version__free_unpacked
                     (MessageGetVersion *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &message_get_version__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   response_get_version__init
                     (ResponseGetVersion         *message)
{
  static const ResponseGetVersion init_value = RESPONSE_GET_VERSION__INIT;
  *message = init_value;
}
size_t response_get_version__get_packed_size
                     (const ResponseGetVersion *message)
{
  assert(message->base.descriptor == &response_get_version__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t response_get_version__pack
                     (const ResponseGetVersion *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &response_get_version__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t response_get_version__pack_to_buffer
                     (const ResponseGetVersion *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &response_get_version__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ResponseGetVersion *
       response_get_version__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ResponseGetVersion *)
     protobuf_c_message_unpack (&response_get_version__descriptor,
                                allocator, len, data);
}
void   response_get_version__free_unpacked
                     (ResponseGetVersion *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &response_get_version__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   message_get_pub_key__init
                     (MessageGetPubKey         *message)
{
  static const MessageGetPubKey init_value = MESSAGE_GET_PUB_KEY__INIT;
  *message = init_value;
}
size_t message_get_pub_key__get_packed_size
                     (const MessageGetPubKey *message)
{
  assert(message->base.descriptor == &message_get_pub_key__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t message_get_pub_key__pack
                     (const MessageGetPubKey *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &message_get_pub_key__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t message_get_pub_key__pack_to_buffer
                     (const MessageGetPubKey *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &message_get_pub_key__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MessageGetPubKey *
       message_get_pub_key__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MessageGetPubKey *)
     protobuf_c_message_unpack (&message_get_pub_key__descriptor,
                                allocator, len, data);
}
void   message_get_pub_key__free_unpacked
                     (MessageGetPubKey *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &message_get_pub_key__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   response_get_pub_key__init
                     (ResponseGetPubKey         *message)
{
  static const ResponseGetPubKey init_value = RESPONSE_GET_PUB_KEY__INIT;
  *message = init_value;
}
size_t response_get_pub_key__get_packed_size
                     (const ResponseGetPubKey *message)
{
  assert(message->base.descriptor == &response_get_pub_key__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t response_get_pub_key__pack
                     (const ResponseGetPubKey *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &response_get_pub_key__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t response_get_pub_key__pack_to_buffer
                     (const ResponseGetPubKey *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &response_get_pub_key__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ResponseGetPubKey *
       response_get_pub_key__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ResponseGetPubKey *)
     protobuf_c_message_unpack (&response_get_pub_key__descriptor,
                                allocator, len, data);
}
void   response_get_pub_key__free_unpacked
                     (ResponseGetPubKey *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &response_get_pub_key__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   message_sign_tx__init
                     (MessageSignTx         *message)
{
  static const MessageSignTx init_value = MESSAGE_SIGN_TX__INIT;
  *message = init_value;
}
size_t message_sign_tx__get_packed_size
                     (const MessageSignTx *message)
{
  assert(message->base.descriptor == &message_sign_tx__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t message_sign_tx__pack
                     (const MessageSignTx *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &message_sign_tx__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t message_sign_tx__pack_to_buffer
                     (const MessageSignTx *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &message_sign_tx__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MessageSignTx *
       message_sign_tx__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MessageSignTx *)
     protobuf_c_message_unpack (&message_sign_tx__descriptor,
                                allocator, len, data);
}
void   message_sign_tx__free_unpacked
                     (MessageSignTx *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &message_sign_tx__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   response_sign_tx__init
                     (ResponseSignTx         *message)
{
  static const ResponseSignTx init_value = RESPONSE_SIGN_TX__INIT;
  *message = init_value;
}
size_t response_sign_tx__get_packed_size
                     (const ResponseSignTx *message)
{
  assert(message->base.descriptor == &response_sign_tx__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t response_sign_tx__pack
                     (const ResponseSignTx *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &response_sign_tx__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t response_sign_tx__pack_to_buffer
                     (const ResponseSignTx *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &response_sign_tx__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ResponseSignTx *
       response_sign_tx__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ResponseSignTx *)
     protobuf_c_message_unpack (&response_sign_tx__descriptor,
                                allocator, len, data);
}
void   response_sign_tx__free_unpacked
                     (ResponseSignTx *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &response_sign_tx__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   response_error__init
                     (ResponseError         *message)
{
  static const ResponseError init_value = RESPONSE_ERROR__INIT;
  *message = init_value;
}
size_t response_error__get_packed_size
                     (const ResponseError *message)
{
  assert(message->base.descriptor == &response_error__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t response_error__pack
                     (const ResponseError *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &response_error__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t response_error__pack_to_buffer
                     (const ResponseError *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &response_error__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ResponseError *
       response_error__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ResponseError *)
     protobuf_c_message_unpack (&response_error__descriptor,
                                allocator, len, data);
}
void   response_error__free_unpacked
                     (ResponseError *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &response_error__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   message__init
                     (Message         *message)
{
  static const Message init_value = MESSAGE__INIT;
  *message = init_value;
}
size_t message__get_packed_size
                     (const Message *message)
{
  assert(message->base.descriptor == &message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t message__pack
                     (const Message *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t message__pack_to_buffer
                     (const Message *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Message *
       message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Message *)
     protobuf_c_message_unpack (&message__descriptor,
                                allocator, len, data);
}
void   message__free_unpacked
                     (Message *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   response__init
                     (Response         *message)
{
  static const Response init_value = RESPONSE__INIT;
  *message = init_value;
}
size_t response__get_packed_size
                     (const Response *message)
{
  assert(message->base.descriptor == &response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t response__pack
                     (const Response *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t response__pack_to_buffer
                     (const Response *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Response *
       response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Response *)
     protobuf_c_message_unpack (&response__descriptor,
                                allocator, len, data);
}
void   response__free_unpacked
                     (Response *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
#define message_get_version__field_descriptors NULL
#define message_get_version__field_indices_by_name NULL
#define message_get_version__number_ranges NULL
const ProtobufCMessageDescriptor message_get_version__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "MessageGetVersion",
  "MessageGetVersion",
  "MessageGetVersion",
  "",
  sizeof(MessageGetVersion),
  0,
  message_get_version__field_descriptors,
  message_get_version__field_indices_by_name,
  0,  message_get_version__number_ranges,
  (ProtobufCMessageInit) message_get_version__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor response_get_version__field_descriptors[1] =
{
  {
    "version",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ResponseGetVersion, version),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned response_get_version__field_indices_by_name[] = {
  0,   /* field[0] = version */
};
static const ProtobufCIntRange response_get_version__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor response_get_version__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ResponseGetVersion",
  "ResponseGetVersion",
  "ResponseGetVersion",
  "",
  sizeof(ResponseGetVersion),
  1,
  response_get_version__field_descriptors,
  response_get_version__field_indices_by_name,
  1,  response_get_version__number_ranges,
  (ProtobufCMessageInit) response_get_version__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define message_get_pub_key__field_descriptors NULL
#define message_get_pub_key__field_indices_by_name NULL
#define message_get_pub_key__number_ranges NULL
const ProtobufCMessageDescriptor message_get_pub_key__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "MessageGetPubKey",
  "MessageGetPubKey",
  "MessageGetPubKey",
  "",
  sizeof(MessageGetPubKey),
  0,
  message_get_pub_key__field_descriptors,
  message_get_pub_key__field_indices_by_name,
  0,  message_get_pub_key__number_ranges,
  (ProtobufCMessageInit) message_get_pub_key__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor response_get_pub_key__field_descriptors[1] =
{
  {
    "pubkey",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(ResponseGetPubKey, pubkey),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned response_get_pub_key__field_indices_by_name[] = {
  0,   /* field[0] = pubkey */
};
static const ProtobufCIntRange response_get_pub_key__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor response_get_pub_key__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ResponseGetPubKey",
  "ResponseGetPubKey",
  "ResponseGetPubKey",
  "",
  sizeof(ResponseGetPubKey),
  1,
  response_get_pub_key__field_descriptors,
  response_get_pub_key__field_indices_by_name,
  1,  response_get_pub_key__number_ranges,
  (ProtobufCMessageInit) response_get_pub_key__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor message_sign_tx__field_descriptors[1] =
{
  {
    "tx",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(MessageSignTx, tx),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned message_sign_tx__field_indices_by_name[] = {
  0,   /* field[0] = tx */
};
static const ProtobufCIntRange message_sign_tx__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor message_sign_tx__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "MessageSignTx",
  "MessageSignTx",
  "MessageSignTx",
  "",
  sizeof(MessageSignTx),
  1,
  message_sign_tx__field_descriptors,
  message_sign_tx__field_indices_by_name,
  1,  message_sign_tx__number_ranges,
  (ProtobufCMessageInit) message_sign_tx__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor response_sign_tx__field_descriptors[2] =
{
  {
    "approved",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(ResponseSignTx, approved),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "signature",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(ResponseSignTx, signature),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned response_sign_tx__field_indices_by_name[] = {
  0,   /* field[0] = approved */
  1,   /* field[1] = signature */
};
static const ProtobufCIntRange response_sign_tx__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor response_sign_tx__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ResponseSignTx",
  "ResponseSignTx",
  "ResponseSignTx",
  "",
  sizeof(ResponseSignTx),
  2,
  response_sign_tx__field_descriptors,
  response_sign_tx__field_indices_by_name,
  1,  response_sign_tx__number_ranges,
  (ProtobufCMessageInit) response_sign_tx__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor response_error__field_descriptors[1] =
{
  {
    "error_msg",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ResponseError, error_msg),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned response_error__field_indices_by_name[] = {
  0,   /* field[0] = error_msg */
};
static const ProtobufCIntRange response_error__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor response_error__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ResponseError",
  "ResponseError",
  "ResponseError",
  "",
  sizeof(ResponseError),
  1,
  response_error__field_descriptors,
  response_error__field_indices_by_name,
  1,  response_error__number_ranges,
  (ProtobufCMessageInit) response_error__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor message__field_descriptors[3] =
{
  {
    "get_version",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Message, message_oneof_case),
    offsetof(Message, get_version),
    &message_get_version__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "get_pubkey",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Message, message_oneof_case),
    offsetof(Message, get_pubkey),
    &message_get_pub_key__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sign_tx",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Message, message_oneof_case),
    offsetof(Message, sign_tx),
    &message_sign_tx__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned message__field_indices_by_name[] = {
  1,   /* field[1] = get_pubkey */
  0,   /* field[0] = get_version */
  2,   /* field[2] = sign_tx */
};
static const ProtobufCIntRange message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Message",
  "Message",
  "Message",
  "",
  sizeof(Message),
  3,
  message__field_descriptors,
  message__field_indices_by_name,
  1,  message__number_ranges,
  (ProtobufCMessageInit) message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor response__field_descriptors[4] =
{
  {
    "get_version",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Response, message_oneof_case),
    offsetof(Response, get_version),
    &response_get_version__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "get_pubkey",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Response, message_oneof_case),
    offsetof(Response, get_pubkey),
    &response_get_pub_key__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sign_tx",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Response, message_oneof_case),
    offsetof(Response, sign_tx),
    &response_sign_tx__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "error",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Response, message_oneof_case),
    offsetof(Response, error),
    &response_error__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned response__field_indices_by_name[] = {
  3,   /* field[3] = error */
  1,   /* field[1] = get_pubkey */
  0,   /* field[0] = get_version */
  2,   /* field[2] = sign_tx */
};
static const ProtobufCIntRange response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Response",
  "Response",
  "Response",
  "",
  sizeof(Response),
  4,
  response__field_descriptors,
  response__field_indices_by_name,
  1,  response__number_ranges,
  (ProtobufCMessageInit) response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
