/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.6-dev */

#ifndef PB_APP_SWAP_PROTOBUF_MESSAGE_PB_H_INCLUDED
#define PB_APP_SWAP_PROTOBUF_MESSAGE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _RequestGetVersion { 
    char dummy_field;
} RequestGetVersion;

typedef struct _RequestInitSell { 
    char dummy_field;
} RequestInitSell;

typedef struct _RequestInitSwap { 
    char dummy_field;
} RequestInitSwap;

typedef PB_BYTES_ARRAY_T(72) Partner_signature_t;
typedef struct _Partner { 
    char name[16]; 
    pb_byte_t pubkey[65]; 
    Partner_signature_t signature; 
} Partner;

typedef struct _ResponseError { 
    char error_msg[65]; 
} ResponseError;

typedef struct _ResponseGetVersion { 
    char version[41]; 
} ResponseGetVersion;

typedef struct _ResponseInitSell { 
    pb_byte_t device_id[32]; 
} ResponseInitSell;

typedef struct _ResponseInitSwap { 
    pb_byte_t device_id[10]; 
} ResponseInitSwap;

typedef PB_BYTES_ARRAY_T(72) ResponseSell_signature_t;
typedef struct _ResponseSell { 
    bool approved; 
    ResponseSell_signature_t signature; 
} ResponseSell;

typedef PB_BYTES_ARRAY_T(256) ResponseSwap_tx_t;
typedef struct _ResponseSwap { 
    bool approved; 
    ResponseSwap_tx_t tx; 
} ResponseSwap;

typedef PB_BYTES_ARRAY_T(256) RequestSell_b64_tx_t;
typedef PB_BYTES_ARRAY_T(72) RequestSell_signature_t;
typedef PB_BYTES_ARRAY_T(16) RequestSell_fee_t;
typedef struct _RequestSell { 
    bool has_partner;
    Partner partner; 
    RequestSell_b64_tx_t b64_tx; 
    RequestSell_signature_t signature; 
    RequestSell_fee_t fee; 
} RequestSell;

typedef PB_BYTES_ARRAY_T(256) RequestSwap_pb_tx_t;
typedef PB_BYTES_ARRAY_T(72) RequestSwap_signature_t;
typedef PB_BYTES_ARRAY_T(16) RequestSwap_fee_t;
typedef struct _RequestSwap { 
    bool has_partner;
    Partner partner; 
    RequestSwap_pb_tx_t pb_tx; 
    RequestSwap_signature_t signature; 
    RequestSwap_fee_t fee; 
    pb_size_t payout_path_count;
    uint32_t payout_path[10]; 
    pb_size_t refund_path_count;
    uint32_t refund_path[10]; 
    pb_byte_t payout_addr_params[1]; 
    pb_byte_t refund_addr_params[1]; 
} RequestSwap;

typedef struct _Response { 
    pb_size_t which_response;
    union {
        ResponseGetVersion get_version;
        ResponseInitSwap init_swap;
        ResponseInitSell init_sell;
        ResponseSwap swap;
        ResponseSell sell;
        ResponseError error;
    } response; 
} Response;

typedef struct _Request { 
    pb_size_t which_request;
    union {
        RequestGetVersion get_version;
        RequestInitSwap init_swap;
        RequestInitSell init_sell;
        RequestSwap swap;
        RequestSell sell;
    } request; 
} Request;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define RequestGetVersion_init_default           {0}
#define ResponseGetVersion_init_default          {""}
#define RequestInitSwap_init_default             {0}
#define ResponseInitSwap_init_default            {{0}}
#define RequestInitSell_init_default             {0}
#define ResponseInitSell_init_default            {{0}}
#define Partner_init_default                     {"", {0}, {0, {0}}}
#define RequestSwap_init_default                 {false, Partner_init_default, {0, {0}}, {0, {0}}, {0, {0}}, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0}, {0}}
#define ResponseSwap_init_default                {0, {0, {0}}}
#define RequestSell_init_default                 {false, Partner_init_default, {0, {0}}, {0, {0}}, {0, {0}}}
#define ResponseSell_init_default                {0, {0, {0}}}
#define ResponseError_init_default               {""}
#define Request_init_default                     {0, {RequestGetVersion_init_default}}
#define Response_init_default                    {0, {ResponseGetVersion_init_default}}
#define RequestGetVersion_init_zero              {0}
#define ResponseGetVersion_init_zero             {""}
#define RequestInitSwap_init_zero                {0}
#define ResponseInitSwap_init_zero               {{0}}
#define RequestInitSell_init_zero                {0}
#define ResponseInitSell_init_zero               {{0}}
#define Partner_init_zero                        {"", {0}, {0, {0}}}
#define RequestSwap_init_zero                    {false, Partner_init_zero, {0, {0}}, {0, {0}}, {0, {0}}, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0}, {0}}
#define ResponseSwap_init_zero                   {0, {0, {0}}}
#define RequestSell_init_zero                    {false, Partner_init_zero, {0, {0}}, {0, {0}}, {0, {0}}}
#define ResponseSell_init_zero                   {0, {0, {0}}}
#define ResponseError_init_zero                  {""}
#define Request_init_zero                        {0, {RequestGetVersion_init_zero}}
#define Response_init_zero                       {0, {ResponseGetVersion_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define Partner_name_tag                         1
#define Partner_pubkey_tag                       2
#define Partner_signature_tag                    3
#define ResponseError_error_msg_tag              1
#define ResponseGetVersion_version_tag           1
#define ResponseInitSell_device_id_tag           1
#define ResponseInitSwap_device_id_tag           1
#define ResponseSell_approved_tag                1
#define ResponseSell_signature_tag               2
#define ResponseSwap_approved_tag                1
#define ResponseSwap_tx_tag                      2
#define RequestSell_partner_tag                  1
#define RequestSell_b64_tx_tag                   2
#define RequestSell_signature_tag                3
#define RequestSell_fee_tag                      4
#define RequestSwap_partner_tag                  1
#define RequestSwap_pb_tx_tag                    2
#define RequestSwap_signature_tag                3
#define RequestSwap_fee_tag                      4
#define RequestSwap_payout_path_tag              5
#define RequestSwap_refund_path_tag              6
#define RequestSwap_payout_addr_params_tag       7
#define RequestSwap_refund_addr_params_tag       8
#define Response_get_version_tag                 1
#define Response_init_swap_tag                   2
#define Response_init_sell_tag                   3
#define Response_swap_tag                        4
#define Response_sell_tag                        5
#define Response_error_tag                       6
#define Request_get_version_tag                  1
#define Request_init_swap_tag                    2
#define Request_init_sell_tag                    3
#define Request_swap_tag                         4
#define Request_sell_tag                         5

/* Struct field encoding specification for nanopb */
#define RequestGetVersion_FIELDLIST(X, a) \

#define RequestGetVersion_CALLBACK NULL
#define RequestGetVersion_DEFAULT NULL

#define ResponseGetVersion_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   version,           1)
#define ResponseGetVersion_CALLBACK NULL
#define ResponseGetVersion_DEFAULT NULL

#define RequestInitSwap_FIELDLIST(X, a) \

#define RequestInitSwap_CALLBACK NULL
#define RequestInitSwap_DEFAULT NULL

#define ResponseInitSwap_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FIXED_LENGTH_BYTES, device_id,         1)
#define ResponseInitSwap_CALLBACK NULL
#define ResponseInitSwap_DEFAULT NULL

#define RequestInitSell_FIELDLIST(X, a) \

#define RequestInitSell_CALLBACK NULL
#define RequestInitSell_DEFAULT NULL

#define ResponseInitSell_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FIXED_LENGTH_BYTES, device_id,         1)
#define ResponseInitSell_CALLBACK NULL
#define ResponseInitSell_DEFAULT NULL

#define Partner_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   name,              1) \
X(a, STATIC,   SINGULAR, FIXED_LENGTH_BYTES, pubkey,            2) \
X(a, STATIC,   SINGULAR, BYTES,    signature,         3)
#define Partner_CALLBACK NULL
#define Partner_DEFAULT NULL

#define RequestSwap_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  partner,           1) \
X(a, STATIC,   SINGULAR, BYTES,    pb_tx,             2) \
X(a, STATIC,   SINGULAR, BYTES,    signature,         3) \
X(a, STATIC,   SINGULAR, BYTES,    fee,               4) \
X(a, STATIC,   REPEATED, UINT32,   payout_path,       5) \
X(a, STATIC,   REPEATED, UINT32,   refund_path,       6) \
X(a, STATIC,   SINGULAR, FIXED_LENGTH_BYTES, payout_addr_params,   7) \
X(a, STATIC,   SINGULAR, FIXED_LENGTH_BYTES, refund_addr_params,   8)
#define RequestSwap_CALLBACK NULL
#define RequestSwap_DEFAULT NULL
#define RequestSwap_partner_MSGTYPE Partner

#define ResponseSwap_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     approved,          1) \
X(a, STATIC,   SINGULAR, BYTES,    tx,                2)
#define ResponseSwap_CALLBACK NULL
#define ResponseSwap_DEFAULT NULL

#define RequestSell_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  partner,           1) \
X(a, STATIC,   SINGULAR, BYTES,    b64_tx,            2) \
X(a, STATIC,   SINGULAR, BYTES,    signature,         3) \
X(a, STATIC,   SINGULAR, BYTES,    fee,               4)
#define RequestSell_CALLBACK NULL
#define RequestSell_DEFAULT NULL
#define RequestSell_partner_MSGTYPE Partner

#define ResponseSell_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     approved,          1) \
X(a, STATIC,   SINGULAR, BYTES,    signature,         2)
#define ResponseSell_CALLBACK NULL
#define ResponseSell_DEFAULT NULL

#define ResponseError_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   error_msg,         1)
#define ResponseError_CALLBACK NULL
#define ResponseError_DEFAULT NULL

#define Request_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,get_version,request.get_version),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,init_swap,request.init_swap),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,init_sell,request.init_sell),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,swap,request.swap),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,sell,request.sell),   5)
#define Request_CALLBACK NULL
#define Request_DEFAULT NULL
#define Request_request_get_version_MSGTYPE RequestGetVersion
#define Request_request_init_swap_MSGTYPE RequestInitSwap
#define Request_request_init_sell_MSGTYPE RequestInitSell
#define Request_request_swap_MSGTYPE RequestSwap
#define Request_request_sell_MSGTYPE RequestSell

#define Response_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,get_version,response.get_version),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,init_swap,response.init_swap),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,init_sell,response.init_sell),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,swap,response.swap),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,sell,response.sell),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,error,response.error),   6)
#define Response_CALLBACK NULL
#define Response_DEFAULT NULL
#define Response_response_get_version_MSGTYPE ResponseGetVersion
#define Response_response_init_swap_MSGTYPE ResponseInitSwap
#define Response_response_init_sell_MSGTYPE ResponseInitSell
#define Response_response_swap_MSGTYPE ResponseSwap
#define Response_response_sell_MSGTYPE ResponseSell
#define Response_response_error_MSGTYPE ResponseError

extern const pb_msgdesc_t RequestGetVersion_msg;
extern const pb_msgdesc_t ResponseGetVersion_msg;
extern const pb_msgdesc_t RequestInitSwap_msg;
extern const pb_msgdesc_t ResponseInitSwap_msg;
extern const pb_msgdesc_t RequestInitSell_msg;
extern const pb_msgdesc_t ResponseInitSell_msg;
extern const pb_msgdesc_t Partner_msg;
extern const pb_msgdesc_t RequestSwap_msg;
extern const pb_msgdesc_t ResponseSwap_msg;
extern const pb_msgdesc_t RequestSell_msg;
extern const pb_msgdesc_t ResponseSell_msg;
extern const pb_msgdesc_t ResponseError_msg;
extern const pb_msgdesc_t Request_msg;
extern const pb_msgdesc_t Response_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define RequestGetVersion_fields &RequestGetVersion_msg
#define ResponseGetVersion_fields &ResponseGetVersion_msg
#define RequestInitSwap_fields &RequestInitSwap_msg
#define ResponseInitSwap_fields &ResponseInitSwap_msg
#define RequestInitSell_fields &RequestInitSell_msg
#define ResponseInitSell_fields &ResponseInitSell_msg
#define Partner_fields &Partner_msg
#define RequestSwap_fields &RequestSwap_msg
#define ResponseSwap_fields &ResponseSwap_msg
#define RequestSell_fields &RequestSell_msg
#define ResponseSell_fields &ResponseSell_msg
#define ResponseError_fields &ResponseError_msg
#define Request_fields &Request_msg
#define Response_fields &Response_msg

/* Maximum encoded size of messages (where known) */
#define Partner_size                             158
#define RequestGetVersion_size                   0
#define RequestInitSell_size                     0
#define RequestInitSwap_size                     0
#define RequestSell_size                         512
#define RequestSwap_size                         638
#define Request_size                             641
#define ResponseError_size                       66
#define ResponseGetVersion_size                  42
#define ResponseInitSell_size                    34
#define ResponseInitSwap_size                    12
#define ResponseSell_size                        76
#define ResponseSwap_size                        261
#define Response_size                            264

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
