/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6-dev */

#include "app-swap/protobuf/message.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(RequestGetVersion, RequestGetVersion, AUTO)


PB_BIND(ResponseGetVersion, ResponseGetVersion, AUTO)


PB_BIND(RequestInitSwap, RequestInitSwap, AUTO)


PB_BIND(ResponseInitSwap, ResponseInitSwap, AUTO)


PB_BIND(RequestInitSell, RequestInitSell, AUTO)


PB_BIND(ResponseInitSell, ResponseInitSell, AUTO)


PB_BIND(Partner, Partner, AUTO)


PB_BIND(RequestSwap, RequestSwap, 2)


PB_BIND(ResponseSwap, ResponseSwap, AUTO)


PB_BIND(RequestSell, RequestSell, 2)


PB_BIND(ResponseSell, ResponseSell, AUTO)


PB_BIND(ResponseError, ResponseError, AUTO)


PB_BIND(Request, Request, 2)


PB_BIND(Response, Response, AUTO)



