# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: swap.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='swap.proto',
  package='ledger_swap',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\nswap.proto\x12\x0bledger_swap\"\xaa\x02\n\x16NewTransactionResponse\x12\x15\n\rpayin_address\x18\x01 \x01(\t\x12\x16\n\x0epayin_extra_id\x18\x02 \x01(\t\x12\x16\n\x0erefund_address\x18\x03 \x01(\t\x12\x17\n\x0frefund_extra_id\x18\x04 \x01(\t\x12\x16\n\x0epayout_address\x18\x05 \x01(\t\x12\x17\n\x0fpayout_extra_id\x18\x06 \x01(\t\x12\x15\n\rcurrency_from\x18\x07 \x01(\t\x12\x13\n\x0b\x63urrency_to\x18\x08 \x01(\t\x12\x1a\n\x12\x61mount_to_provider\x18\t \x01(\x0c\x12\x18\n\x10\x61mount_to_wallet\x18\n \x01(\x0c\x12\x1d\n\x15\x64\x65vice_transaction_id\x18\x0b \x01(\t\"1\n\x08UDecimal\x12\x13\n\x0b\x63oefficient\x18\x01 \x01(\x0c\x12\x10\n\x08\x65xponent\x18\x02 \x01(\r\"\xc3\x01\n\x0fNewSellResponse\x12\x14\n\x0ctrader_email\x18\x01 \x01(\t\x12\x13\n\x0bin_currency\x18\x02 \x01(\t\x12\x11\n\tin_amount\x18\x03 \x01(\x0c\x12\x12\n\nin_address\x18\x04 \x01(\t\x12\x14\n\x0cout_currency\x18\x05 \x01(\t\x12)\n\nout_amount\x18\x06 \x01(\x0b\x32\x15.ledger_swap.UDecimal\x12\x1d\n\x15\x64\x65vice_transaction_id\x18\x07 \x01(\x0c\x62\x06proto3'
)




_NEWTRANSACTIONRESPONSE = _descriptor.Descriptor(
  name='NewTransactionResponse',
  full_name='ledger_swap.NewTransactionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='payin_address', full_name='ledger_swap.NewTransactionResponse.payin_address', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='payin_extra_id', full_name='ledger_swap.NewTransactionResponse.payin_extra_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='refund_address', full_name='ledger_swap.NewTransactionResponse.refund_address', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='refund_extra_id', full_name='ledger_swap.NewTransactionResponse.refund_extra_id', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='payout_address', full_name='ledger_swap.NewTransactionResponse.payout_address', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='payout_extra_id', full_name='ledger_swap.NewTransactionResponse.payout_extra_id', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='currency_from', full_name='ledger_swap.NewTransactionResponse.currency_from', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='currency_to', full_name='ledger_swap.NewTransactionResponse.currency_to', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='amount_to_provider', full_name='ledger_swap.NewTransactionResponse.amount_to_provider', index=8,
      number=9, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='amount_to_wallet', full_name='ledger_swap.NewTransactionResponse.amount_to_wallet', index=9,
      number=10, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='device_transaction_id', full_name='ledger_swap.NewTransactionResponse.device_transaction_id', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=326,
)


_UDECIMAL = _descriptor.Descriptor(
  name='UDecimal',
  full_name='ledger_swap.UDecimal',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='coefficient', full_name='ledger_swap.UDecimal.coefficient', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='exponent', full_name='ledger_swap.UDecimal.exponent', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=328,
  serialized_end=377,
)


_NEWSELLRESPONSE = _descriptor.Descriptor(
  name='NewSellResponse',
  full_name='ledger_swap.NewSellResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='trader_email', full_name='ledger_swap.NewSellResponse.trader_email', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='in_currency', full_name='ledger_swap.NewSellResponse.in_currency', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='in_amount', full_name='ledger_swap.NewSellResponse.in_amount', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='in_address', full_name='ledger_swap.NewSellResponse.in_address', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='out_currency', full_name='ledger_swap.NewSellResponse.out_currency', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='out_amount', full_name='ledger_swap.NewSellResponse.out_amount', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='device_transaction_id', full_name='ledger_swap.NewSellResponse.device_transaction_id', index=6,
      number=7, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=380,
  serialized_end=575,
)

_NEWSELLRESPONSE.fields_by_name['out_amount'].message_type = _UDECIMAL
DESCRIPTOR.message_types_by_name['NewTransactionResponse'] = _NEWTRANSACTIONRESPONSE
DESCRIPTOR.message_types_by_name['UDecimal'] = _UDECIMAL
DESCRIPTOR.message_types_by_name['NewSellResponse'] = _NEWSELLRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NewTransactionResponse = _reflection.GeneratedProtocolMessageType('NewTransactionResponse', (_message.Message,), {
  'DESCRIPTOR' : _NEWTRANSACTIONRESPONSE,
  '__module__' : 'swap_pb2'
  # @@protoc_insertion_point(class_scope:ledger_swap.NewTransactionResponse)
  })
_sym_db.RegisterMessage(NewTransactionResponse)

UDecimal = _reflection.GeneratedProtocolMessageType('UDecimal', (_message.Message,), {
  'DESCRIPTOR' : _UDECIMAL,
  '__module__' : 'swap_pb2'
  # @@protoc_insertion_point(class_scope:ledger_swap.UDecimal)
  })
_sym_db.RegisterMessage(UDecimal)

NewSellResponse = _reflection.GeneratedProtocolMessageType('NewSellResponse', (_message.Message,), {
  'DESCRIPTOR' : _NEWSELLRESPONSE,
  '__module__' : 'swap_pb2'
  # @@protoc_insertion_point(class_scope:ledger_swap.NewSellResponse)
  })
_sym_db.RegisterMessage(NewSellResponse)


# @@protoc_insertion_point(module_scope)
