/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6-dev */

#include "app-swap/protobuf/swap.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(ledger_swap_NewTransactionResponse, ledger_swap_NewTransactionResponse, 2)


PB_BIND(ledger_swap_UDecimal, ledger_swap_UDecimal, AUTO)


PB_BIND(ledger_swap_NewSellResponse, ledger_swap_NewSellResponse, AUTO)



