# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message-nonano.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14message-nonano.proto\"\x13\n\x11RequestGetVersion\"%\n\x12ResponseGetVersion\x12\x0f\n\x07version\x18\x01 \x01(\t\"I\n\x10RequestGetPubKey\x12\x0c\n\x04path\x18\x01 \x03(\r\x12\x0f\n\x07\x63onfirm\x18\x02 \x01(\x08\x12\x16\n\x0eget_chain_code\x18\x03 \x01(\x08\"Z\n\x11ResponseGetPubKey\x12\x10\n\x08\x61pproved\x18\x01 \x01(\x08\x12\x0e\n\x06pubkey\x18\x02 \x01(\x0c\x12\x0f\n\x07\x61\x64\x64ress\x18\x03 \x01(\t\x12\x12\n\nchain_code\x18\x04 \x01(\x0c\"?\n\rRequestSignTx\x12\x0c\n\x04path\x18\x01 \x03(\r\x12\x0e\n\x06raw_tx\x18\x02 \x01(\x0c\x12\x10\n\x08\x63hain_id\x18\x03 \x01(\x04\"5\n\x0eResponseSignTx\x12\x10\n\x08\x61pproved\x18\x01 \x01(\x08\x12\x11\n\tsignature\x18\x02 \x01(\x0c\"\"\n\rResponseError\x12\x11\n\terror_msg\x18\x01 \x01(\t\"\x91\x01\n\x07Request\x12)\n\x0bget_version\x18\x01 \x01(\x0b\x32\x12.RequestGetVersionH\x00\x12\'\n\nget_pubkey\x18\x02 \x01(\x0b\x32\x11.RequestGetPubKeyH\x00\x12!\n\x07sign_tx\x18\x03 \x01(\x0b\x32\x0e.RequestSignTxH\x00\x42\x0f\n\rmessage_oneof\"\xb6\x01\n\x08Response\x12*\n\x0bget_version\x18\x01 \x01(\x0b\x32\x13.ResponseGetVersionH\x00\x12(\n\nget_pubkey\x18\x02 \x01(\x0b\x32\x12.ResponseGetPubKeyH\x00\x12\"\n\x07sign_tx\x18\x03 \x01(\x0b\x32\x0f.ResponseSignTxH\x00\x12\x1f\n\x05\x65rror\x18\x04 \x01(\x0b\x32\x0e.ResponseErrorH\x00\x42\x0f\n\rmessage_oneofb\x06proto3')



_REQUESTGETVERSION = DESCRIPTOR.message_types_by_name['RequestGetVersion']
_RESPONSEGETVERSION = DESCRIPTOR.message_types_by_name['ResponseGetVersion']
_REQUESTGETPUBKEY = DESCRIPTOR.message_types_by_name['RequestGetPubKey']
_RESPONSEGETPUBKEY = DESCRIPTOR.message_types_by_name['ResponseGetPubKey']
_REQUESTSIGNTX = DESCRIPTOR.message_types_by_name['RequestSignTx']
_RESPONSESIGNTX = DESCRIPTOR.message_types_by_name['ResponseSignTx']
_RESPONSEERROR = DESCRIPTOR.message_types_by_name['ResponseError']
_REQUEST = DESCRIPTOR.message_types_by_name['Request']
_RESPONSE = DESCRIPTOR.message_types_by_name['Response']
RequestGetVersion = _reflection.GeneratedProtocolMessageType('RequestGetVersion', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTGETVERSION,
  '__module__' : 'message_nonano_pb2'
  # @@protoc_insertion_point(class_scope:RequestGetVersion)
  })
_sym_db.RegisterMessage(RequestGetVersion)

ResponseGetVersion = _reflection.GeneratedProtocolMessageType('ResponseGetVersion', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSEGETVERSION,
  '__module__' : 'message_nonano_pb2'
  # @@protoc_insertion_point(class_scope:ResponseGetVersion)
  })
_sym_db.RegisterMessage(ResponseGetVersion)

RequestGetPubKey = _reflection.GeneratedProtocolMessageType('RequestGetPubKey', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTGETPUBKEY,
  '__module__' : 'message_nonano_pb2'
  # @@protoc_insertion_point(class_scope:RequestGetPubKey)
  })
_sym_db.RegisterMessage(RequestGetPubKey)

ResponseGetPubKey = _reflection.GeneratedProtocolMessageType('ResponseGetPubKey', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSEGETPUBKEY,
  '__module__' : 'message_nonano_pb2'
  # @@protoc_insertion_point(class_scope:ResponseGetPubKey)
  })
_sym_db.RegisterMessage(ResponseGetPubKey)

RequestSignTx = _reflection.GeneratedProtocolMessageType('RequestSignTx', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTSIGNTX,
  '__module__' : 'message_nonano_pb2'
  # @@protoc_insertion_point(class_scope:RequestSignTx)
  })
_sym_db.RegisterMessage(RequestSignTx)

ResponseSignTx = _reflection.GeneratedProtocolMessageType('ResponseSignTx', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSESIGNTX,
  '__module__' : 'message_nonano_pb2'
  # @@protoc_insertion_point(class_scope:ResponseSignTx)
  })
_sym_db.RegisterMessage(ResponseSignTx)

ResponseError = _reflection.GeneratedProtocolMessageType('ResponseError', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSEERROR,
  '__module__' : 'message_nonano_pb2'
  # @@protoc_insertion_point(class_scope:ResponseError)
  })
_sym_db.RegisterMessage(ResponseError)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'message_nonano_pb2'
  # @@protoc_insertion_point(class_scope:Request)
  })
_sym_db.RegisterMessage(Request)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'message_nonano_pb2'
  # @@protoc_insertion_point(class_scope:Response)
  })
_sym_db.RegisterMessage(Response)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUESTGETVERSION._serialized_start=24
  _REQUESTGETVERSION._serialized_end=43
  _RESPONSEGETVERSION._serialized_start=45
  _RESPONSEGETVERSION._serialized_end=82
  _REQUESTGETPUBKEY._serialized_start=84
  _REQUESTGETPUBKEY._serialized_end=157
  _RESPONSEGETPUBKEY._serialized_start=159
  _RESPONSEGETPUBKEY._serialized_end=249
  _REQUESTSIGNTX._serialized_start=251
  _REQUESTSIGNTX._serialized_end=314
  _RESPONSESIGNTX._serialized_start=316
  _RESPONSESIGNTX._serialized_end=369
  _RESPONSEERROR._serialized_start=371
  _RESPONSEERROR._serialized_end=405
  _REQUEST._serialized_start=408
  _REQUEST._serialized_end=553
  _RESPONSE._serialized_start=556
  _RESPONSE._serialized_end=738
# @@protoc_insertion_point(module_scope)
