/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6-dev */

#include "app-ethereum/protobuf/message.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(RequestGetVersion, RequestGetVersion, AUTO)


PB_BIND(ResponseGetVersion, ResponseGetVersion, AUTO)


PB_BIND(RequestGetPubKey, RequestGetPubKey, AUTO)


PB_BIND(ResponseGetPubKey, ResponseGetPubKey, AUTO)


PB_BIND(RequestSignTx, RequestSignTx, 2)


PB_BIND(ResponseSignTx, ResponseSignTx, AUTO)


PB_BIND(RequestSignMsg, RequestSignMsg, 2)


PB_BIND(ResponseSignMsg, ResponseSignMsg, AUTO)


PB_BIND(RequestSignEip712, RequestSignEip712, 2)


PB_BIND(ResponseSignEip712, ResponseSignEip712, AUTO)


PB_BIND(ResponseError, ResponseError, AUTO)


PB_BIND(Request, Request, 2)


PB_BIND(Response, Response, AUTO)



