/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: message.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "message.pb-c.h"
void   request_get_version__init
                     (RequestGetVersion         *message)
{
  static RequestGetVersion init_value = REQUEST_GET_VERSION__INIT;
  *message = init_value;
}
size_t request_get_version__get_packed_size
                     (const RequestGetVersion *message)
{
  assert(message->base.descriptor == &request_get_version__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t request_get_version__pack
                     (const RequestGetVersion *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &request_get_version__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t request_get_version__pack_to_buffer
                     (const RequestGetVersion *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &request_get_version__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RequestGetVersion *
       request_get_version__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RequestGetVersion *)
     protobuf_c_message_unpack (&request_get_version__descriptor,
                                allocator, len, data);
}
void   request_get_version__free_unpacked
                     (RequestGetVersion *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &request_get_version__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   response_get_version__init
                     (ResponseGetVersion         *message)
{
  static ResponseGetVersion init_value = RESPONSE_GET_VERSION__INIT;
  *message = init_value;
}
size_t response_get_version__get_packed_size
                     (const ResponseGetVersion *message)
{
  assert(message->base.descriptor == &response_get_version__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t response_get_version__pack
                     (const ResponseGetVersion *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &response_get_version__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t response_get_version__pack_to_buffer
                     (const ResponseGetVersion *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &response_get_version__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ResponseGetVersion *
       response_get_version__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ResponseGetVersion *)
     protobuf_c_message_unpack (&response_get_version__descriptor,
                                allocator, len, data);
}
void   response_get_version__free_unpacked
                     (ResponseGetVersion *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &response_get_version__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   request_get_pub_key__init
                     (RequestGetPubKey         *message)
{
  static RequestGetPubKey init_value = REQUEST_GET_PUB_KEY__INIT;
  *message = init_value;
}
size_t request_get_pub_key__get_packed_size
                     (const RequestGetPubKey *message)
{
  assert(message->base.descriptor == &request_get_pub_key__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t request_get_pub_key__pack
                     (const RequestGetPubKey *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &request_get_pub_key__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t request_get_pub_key__pack_to_buffer
                     (const RequestGetPubKey *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &request_get_pub_key__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RequestGetPubKey *
       request_get_pub_key__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RequestGetPubKey *)
     protobuf_c_message_unpack (&request_get_pub_key__descriptor,
                                allocator, len, data);
}
void   request_get_pub_key__free_unpacked
                     (RequestGetPubKey *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &request_get_pub_key__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   response_get_pub_key__init
                     (ResponseGetPubKey         *message)
{
  static ResponseGetPubKey init_value = RESPONSE_GET_PUB_KEY__INIT;
  *message = init_value;
}
size_t response_get_pub_key__get_packed_size
                     (const ResponseGetPubKey *message)
{
  assert(message->base.descriptor == &response_get_pub_key__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t response_get_pub_key__pack
                     (const ResponseGetPubKey *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &response_get_pub_key__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t response_get_pub_key__pack_to_buffer
                     (const ResponseGetPubKey *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &response_get_pub_key__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ResponseGetPubKey *
       response_get_pub_key__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ResponseGetPubKey *)
     protobuf_c_message_unpack (&response_get_pub_key__descriptor,
                                allocator, len, data);
}
void   response_get_pub_key__free_unpacked
                     (ResponseGetPubKey *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &response_get_pub_key__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   request_sign_tx__init
                     (RequestSignTx         *message)
{
  static RequestSignTx init_value = REQUEST_SIGN_TX__INIT;
  *message = init_value;
}
size_t request_sign_tx__get_packed_size
                     (const RequestSignTx *message)
{
  assert(message->base.descriptor == &request_sign_tx__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t request_sign_tx__pack
                     (const RequestSignTx *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &request_sign_tx__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t request_sign_tx__pack_to_buffer
                     (const RequestSignTx *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &request_sign_tx__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RequestSignTx *
       request_sign_tx__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RequestSignTx *)
     protobuf_c_message_unpack (&request_sign_tx__descriptor,
                                allocator, len, data);
}
void   request_sign_tx__free_unpacked
                     (RequestSignTx *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &request_sign_tx__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   response_sign_tx__init
                     (ResponseSignTx         *message)
{
  static ResponseSignTx init_value = RESPONSE_SIGN_TX__INIT;
  *message = init_value;
}
size_t response_sign_tx__get_packed_size
                     (const ResponseSignTx *message)
{
  assert(message->base.descriptor == &response_sign_tx__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t response_sign_tx__pack
                     (const ResponseSignTx *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &response_sign_tx__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t response_sign_tx__pack_to_buffer
                     (const ResponseSignTx *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &response_sign_tx__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ResponseSignTx *
       response_sign_tx__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ResponseSignTx *)
     protobuf_c_message_unpack (&response_sign_tx__descriptor,
                                allocator, len, data);
}
void   response_sign_tx__free_unpacked
                     (ResponseSignTx *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &response_sign_tx__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   response_error__init
                     (ResponseError         *message)
{
  static ResponseError init_value = RESPONSE_ERROR__INIT;
  *message = init_value;
}
size_t response_error__get_packed_size
                     (const ResponseError *message)
{
  assert(message->base.descriptor == &response_error__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t response_error__pack
                     (const ResponseError *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &response_error__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t response_error__pack_to_buffer
                     (const ResponseError *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &response_error__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ResponseError *
       response_error__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ResponseError *)
     protobuf_c_message_unpack (&response_error__descriptor,
                                allocator, len, data);
}
void   response_error__free_unpacked
                     (ResponseError *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &response_error__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   request__init
                     (Request         *message)
{
  static Request init_value = REQUEST__INIT;
  *message = init_value;
}
size_t request__get_packed_size
                     (const Request *message)
{
  assert(message->base.descriptor == &request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t request__pack
                     (const Request *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t request__pack_to_buffer
                     (const Request *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Request *
       request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Request *)
     protobuf_c_message_unpack (&request__descriptor,
                                allocator, len, data);
}
void   request__free_unpacked
                     (Request *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   response__init
                     (Response         *message)
{
  static Response init_value = RESPONSE__INIT;
  *message = init_value;
}
size_t response__get_packed_size
                     (const Response *message)
{
  assert(message->base.descriptor == &response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t response__pack
                     (const Response *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t response__pack_to_buffer
                     (const Response *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Response *
       response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Response *)
     protobuf_c_message_unpack (&response__descriptor,
                                allocator, len, data);
}
void   response__free_unpacked
                     (Response *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
#define request_get_version__field_descriptors NULL
#define request_get_version__field_indices_by_name NULL
#define request_get_version__number_ranges NULL
const ProtobufCMessageDescriptor request_get_version__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RequestGetVersion",
  "RequestGetVersion",
  "RequestGetVersion",
  "",
  sizeof(RequestGetVersion),
  0,
  request_get_version__field_descriptors,
  request_get_version__field_indices_by_name,
  0,  request_get_version__number_ranges,
  (ProtobufCMessageInit) request_get_version__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor response_get_version__field_descriptors[1] =
{
  {
    "version",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ResponseGetVersion, version),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned response_get_version__field_indices_by_name[] = {
  0,   /* field[0] = version */
};
static const ProtobufCIntRange response_get_version__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor response_get_version__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ResponseGetVersion",
  "ResponseGetVersion",
  "ResponseGetVersion",
  "",
  sizeof(ResponseGetVersion),
  1,
  response_get_version__field_descriptors,
  response_get_version__field_indices_by_name,
  1,  response_get_version__number_ranges,
  (ProtobufCMessageInit) response_get_version__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor request_get_pub_key__field_descriptors[3] =
{
  {
    "path",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(RequestGetPubKey, n_path),
    offsetof(RequestGetPubKey, path),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "confirm",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(RequestGetPubKey, has_confirm),
    offsetof(RequestGetPubKey, confirm),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "get_chain_code",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(RequestGetPubKey, has_get_chain_code),
    offsetof(RequestGetPubKey, get_chain_code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned request_get_pub_key__field_indices_by_name[] = {
  1,   /* field[1] = confirm */
  2,   /* field[2] = get_chain_code */
  0,   /* field[0] = path */
};
static const ProtobufCIntRange request_get_pub_key__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor request_get_pub_key__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RequestGetPubKey",
  "RequestGetPubKey",
  "RequestGetPubKey",
  "",
  sizeof(RequestGetPubKey),
  3,
  request_get_pub_key__field_descriptors,
  request_get_pub_key__field_indices_by_name,
  1,  request_get_pub_key__number_ranges,
  (ProtobufCMessageInit) request_get_pub_key__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor response_get_pub_key__field_descriptors[4] =
{
  {
    "approved",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(ResponseGetPubKey, has_approved),
    offsetof(ResponseGetPubKey, approved),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pubkey",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(ResponseGetPubKey, has_pubkey),
    offsetof(ResponseGetPubKey, pubkey),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "address",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(ResponseGetPubKey, has_address),
    offsetof(ResponseGetPubKey, address),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "chain_code",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(ResponseGetPubKey, has_chain_code),
    offsetof(ResponseGetPubKey, chain_code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned response_get_pub_key__field_indices_by_name[] = {
  2,   /* field[2] = address */
  0,   /* field[0] = approved */
  3,   /* field[3] = chain_code */
  1,   /* field[1] = pubkey */
};
static const ProtobufCIntRange response_get_pub_key__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor response_get_pub_key__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ResponseGetPubKey",
  "ResponseGetPubKey",
  "ResponseGetPubKey",
  "",
  sizeof(ResponseGetPubKey),
  4,
  response_get_pub_key__field_descriptors,
  response_get_pub_key__field_indices_by_name,
  1,  response_get_pub_key__number_ranges,
  (ProtobufCMessageInit) response_get_pub_key__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor request_sign_tx__field_descriptors[1] =
{
  {
    "tx",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(RequestSignTx, has_tx),
    offsetof(RequestSignTx, tx),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned request_sign_tx__field_indices_by_name[] = {
  0,   /* field[0] = tx */
};
static const ProtobufCIntRange request_sign_tx__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor request_sign_tx__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RequestSignTx",
  "RequestSignTx",
  "RequestSignTx",
  "",
  sizeof(RequestSignTx),
  1,
  request_sign_tx__field_descriptors,
  request_sign_tx__field_indices_by_name,
  1,  request_sign_tx__number_ranges,
  (ProtobufCMessageInit) request_sign_tx__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor response_sign_tx__field_descriptors[2] =
{
  {
    "approved",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(ResponseSignTx, has_approved),
    offsetof(ResponseSignTx, approved),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "signature",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(ResponseSignTx, has_signature),
    offsetof(ResponseSignTx, signature),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned response_sign_tx__field_indices_by_name[] = {
  0,   /* field[0] = approved */
  1,   /* field[1] = signature */
};
static const ProtobufCIntRange response_sign_tx__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor response_sign_tx__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ResponseSignTx",
  "ResponseSignTx",
  "ResponseSignTx",
  "",
  sizeof(ResponseSignTx),
  2,
  response_sign_tx__field_descriptors,
  response_sign_tx__field_indices_by_name,
  1,  response_sign_tx__number_ranges,
  (ProtobufCMessageInit) response_sign_tx__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor response_error__field_descriptors[1] =
{
  {
    "error_msg",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ResponseError, error_msg),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned response_error__field_indices_by_name[] = {
  0,   /* field[0] = error_msg */
};
static const ProtobufCIntRange response_error__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor response_error__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ResponseError",
  "ResponseError",
  "ResponseError",
  "",
  sizeof(ResponseError),
  1,
  response_error__field_descriptors,
  response_error__field_indices_by_name,
  1,  response_error__number_ranges,
  (ProtobufCMessageInit) response_error__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor request__field_descriptors[3] =
{
  {
    "get_version",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Request, message_oneof_case),
    offsetof(Request, get_version),
    &request_get_version__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "get_pubkey",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Request, message_oneof_case),
    offsetof(Request, get_pubkey),
    &request_get_pub_key__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sign_tx",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Request, message_oneof_case),
    offsetof(Request, sign_tx),
    &request_sign_tx__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned request__field_indices_by_name[] = {
  1,   /* field[1] = get_pubkey */
  0,   /* field[0] = get_version */
  2,   /* field[2] = sign_tx */
};
static const ProtobufCIntRange request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Request",
  "Request",
  "Request",
  "",
  sizeof(Request),
  3,
  request__field_descriptors,
  request__field_indices_by_name,
  1,  request__number_ranges,
  (ProtobufCMessageInit) request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor response__field_descriptors[4] =
{
  {
    "get_version",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Response, message_oneof_case),
    offsetof(Response, get_version),
    &response_get_version__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "get_pubkey",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Response, message_oneof_case),
    offsetof(Response, get_pubkey),
    &response_get_pub_key__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sign_tx",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Response, message_oneof_case),
    offsetof(Response, sign_tx),
    &response_sign_tx__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "error",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Response, message_oneof_case),
    offsetof(Response, error),
    &response_error__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned response__field_indices_by_name[] = {
  3,   /* field[3] = error */
  1,   /* field[1] = get_pubkey */
  0,   /* field[0] = get_version */
  2,   /* field[2] = sign_tx */
};
static const ProtobufCIntRange response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Response",
  "Response",
  "Response",
  "",
  sizeof(Response),
  4,
  response__field_descriptors,
  response__field_indices_by_name,
  1,  response__number_ranges,
  (ProtobufCMessageInit) response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
