# Build the RISC-V apps

name: RISC-V apps

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Build apps
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/ledgerhq/app-streaming-builder:latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.PAT }}

      - name: Build
        working-directory: ./app
        run: |
           cmake -Bbuild -H.
           make -j -C build/
